version: '3.8'

services:
  kavita:
    image: jvmilazz0/kavita:latest
    environment:
      - TZ=Europe/Moscow
    volumes:
      - ./data/kavita/books:/books
      - ./data/kavita/manga:/manga
      - ./data/kavita/config:/kavita/config
    ports:
      - "5000:5000"
    restart: unless-stopped
    networks:
      - hosting-network

  userinfo-backend:
    image: yvv4docker/userinfo-backend:latest
    env_file:
      - .env
    volumes:
      - ./data/userinfo/.env:/root/.env
    networks:
      - hosting-network
  
  userinfo-frontend:
    image: yvv4docker/userinfo-frontend:latest
    ports:
      - "8080:8080"
    depends_on:
      - userinfo-backend
    env_file:
      - .env
    volumes:
      - ./data/userinfo/.env:/app/.env
    networks:
      - hosting-network

  nginx:
    image: nginx:latest
    ports:
      # - "80:80" # HTTP disabled
      - "443:443"
      - "8118:8118"
    volumes:
      - ./data/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      # Own-signed
      # - ./data/nginx/certs/mycert.crt:/etc/nginx/certs/mycert.crt:ro
      # - ./data/nginx/certs/mykey.key:/etc/nginx/certs/mykey.key:ro
      # YVV
      - ./data/nginx/certs/yvv-fullchain.pem:/etc/nginx/certs/yvv-fullchain.pem:ro
      - ./data/nginx/certs/yvv-privkey.pem:/etc/nginx/certs/yvv-privkey.pem:ro
      # Playmore
      - ./data/nginx/certs/playmore-fullchain.pem:/etc/nginx/certs/playmore-fullchain.pem:ro
      - ./data/nginx/certs/playmore-privkey.pem:/etc/nginx/certs/playmore-privkey.pem:ro
      # Auth-based
      # - ./data/nginx/passwd:/etc/nginx/passwd:ro
    depends_on:
      - kavita
    restart: unless-stopped
    networks:
      - hosting-network

networks:
  hosting-network:
    driver: bridge
