---
services:
  kavita:
    image: jvmilazz0/kavita:latest
    environment:
      - TZ=Europe/Moscow
    volumes:
      - ./data/kavita/books:/books
      - ./data/kavita/manga:/manga
      - ./data/kavita/config:/kavita/config
    ports:
      - "5001:5000"
    restart: unless-stopped

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./data/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - kavita
    restart: unless-stopped