version: '3.8'

services:
  kavita:
    image: jvmilazz0/kavita:latest
    environment:
      - TZ=Europe/Moscow
    volumes:
      - ./data/kavita/books:/books
      - ./data/kavita/manga:/manga
      - ./data/kavita/config:/kavita/config
    # ports:
    #   - "5000:5000"
    networks:
      - hosting-network
    restart: no

  userinfo-backend:
    image: yvv4docker/userinfo-backend:latest
    env_file:
      - ./data/userinfo/.env
    # volumes:
    #   - ./data/userinfo/.env:/root/.env
    ports:
      - "8000:8000"
    networks:
      - hosting-network
    restart: no
  
  userinfo-frontend:
    image: yvv4docker/userinfo-frontend:latest
    ports:
      - "8080:8080"
    depends_on:
      - userinfo-backend
    env_file:
      - ./data/userinfo/.env
    networks:
      - hosting-network
    restart: no

  nginx:
    image: nginx:latest
    ports:
      # - "80:80" # HTTP disabled
      - "443:443"
    volumes:
      - ./data/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      # Own-signed
      # - ./data/nginx/certs/mycert.crt:/etc/nginx/certs/mycert.crt:ro
      # - ./data/nginx/certs/mykey.key:/etc/nginx/certs/mykey.key:ro
      # YVV
      - ./data/nginx/certs/yvv-fullchain.pem:/etc/nginx/certs/yvv-fullchain.pem:ro
      - ./data/nginx/certs/yvv-privkey.pem:/etc/nginx/certs/yvv-privkey.pem:ro
      # Playmore
      - ./data/nginx/certs/playmore-fullchain.pem:/etc/nginx/certs/playmore-fullchain.pem:ro
      - ./data/nginx/certs/playmore-privkey.pem:/etc/nginx/certs/playmore-privkey.pem:ro
      # Auth-based
      # - ./data/nginx/passwd:/etc/nginx/passwd:ro
    depends_on:
      - kavita
      - userinfo-frontend
      - userinfo-backend
    networks:
      - hosting-network
    restart: no

  tor:
    image: dperson/torproxy:latest
    container_name: hosting-srv-tor
    restart: unless-stopped
    ports:
      - "127.0.0.1:9050:9050"  # SOCKS5
      - "127.0.0.1:9051:9051"  # Control port (если нужен)
      - "127.0.0.1:5353:5353"  # DNS
    volumes:
      - ./data/tor/data:/var/lib/tor     # Постоянные данные Tor
      - ./data/tor/torrc:/etc/tor/torrc  # Кастомный конфиг
    environment:
      - TZ=Europe/Moscow
      - LOG_LEVEL=notice
    networks:
      - hosting-network

  firefox:
    image: lscr.io/linuxserver/firefox:latest
    container_name: firefox
    volumes:
      - ./data/firefox:/config:rw
    shm_size: 2g
    ports:
      - 127.0.0.1:3000:3000
    restart: on-failure:2

networks:
  hosting-network:
    driver: bridge
