version: '3.8'

services:
  kavita:
    image: jvmilazz0/kavita:latest
    environment:
      - TZ=Europe/Moscow
    volumes:
      - ./data/kavita/books:/books
      - ./data/kavita/manga:/manga
      - ./data/kavita/config:/kavita/config
    ports:
      - "5000:5000"
    restart: unless-stopped

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./data/nginx/certs/mycert.crt:/etc/nginx/certs/mycert.crt:ro
      - ./data/nginx/certs/mykey.key:/etc/nginx/certs/mykey.key:ro
    depends_on:
      - kavita
    restart: unless-stopped